### ISSUE TITLE
Binary key not provided anymore, how to authenticate with api key and secret?

### ISSUE THREAD

**Issue by satyavh** [mopidy/pyspotify#200] opened 2019-08-13 07:39 UTC
From the docs:

2. Find the libspotify application keys management page and request an application key for your application.
3. Once the key is issued, download the “binary” version. The “C code” version of the key will not work with pyspotify.

But that page doesn't exist anymore in the Spotify api dashboard, it doesn't seem possible to download the binary key. 

The dashboard now simply provides api key and secret. 
How can PySpotify be used with just an api key and secret?

**Comment by kingosticks** [comment] 2019-08-13 08:00
It cannot, you need an app key. Existing binary keys still work but Spotify have stopped issuing new ones. We should assume this isn't going to change and make this clearer in the docs. (duplicate of #197)

**Closed by kingosticks** 2019-08-13 08:00 UTC
