### ISSUE TITLE
function do_search error now!

### ISSUE THREAD

**Issue by hoangphuong** [mopidy/pyspotify#184] opened 2016-02-18 08:40 UTC
function do_search error now!
![screen shot 2016-02-18 at 15 34 38](https://cloud.githubusercontent.com/assets/4811620/13137825/10911fee-d656-11e5-8c7e-081b3050bcdc.png)

**Comment by trygveaa** [comment] 2016-02-18 08:45
This is a duplicate of #183. For more info see mopidy/mopidy-spotify#89 and https://jodal.no/2016/02/18/guide-to-poor-api-management/.

Spotify deactivated their Metadata API, which apparently libspotify used for search. libspotify is deprecated and will probably not get any fix for this.

The question is if pyspotify should remain a simple wrapper around libspotify, or if it should do more and replace the broken functionality.

I'll close this issue, as #183 is open for this.

**Closed** 2016-02-18 09:40 UTC
