### ISSUE TITLE
bitrate doesn´t change

### ISSUE THREAD

**Issue by Adi146** [mopidy/pyspotify#156] opened 2015-03-31 13:07 UTC
Hi, 
I am recording a raw pcm file, by writing the received frames from the on_music_delivery callback to a file. If I change the bitrate with session.preferred_bitrate(spotify.Bitrate.BITRATE_320k), the file has the same size as with 96k.

**Comment by jodal** [comment] 2015-03-31 14:52
Can you reproduce this if you remove the cache in between the two runs? I'm
guessing that it doesn't download the track in better bitrate since it
already has the track cached.

**Comment by Adi146** [comment] 2015-03-31 14:59
There is no difference, if I delete the tmp folder between the downloads. The size is still the same.

**Comment by Adi146** [comment] 2015-04-08 09:31
Hi,
is it possible, that the option to set the bitrate is just useless?
libspotify returns always 44,1kHz sample rate, 2 channels and 16 bit sample type.
So the bitrate should always be the same, cause bits/s = samplerate * sampletype * channels.
Or am I wrong?

**Comment by jodal** [comment] 2015-04-08 09:35
Ah, you're pointing out something I didn't think about at all when you first files this issue:

`session.preferred_bitrate()` adjusts the bitrate off the Ogg Vorbis audio data that Spotify use internally. Higher preferred bitrate should give you better audio quality. However, the audio data we get is always raw PCM audio data with 44.1kHZ sample rate, 2 channels and 16 bit sample. Since we always get raw PCM data out changing the internal Ogg Vorbis bitrate will not give visible results in the raw PCM data you get, but hopefully audible results.

So, maybe this isn't a bug at all?

**Comment by Adi146** [comment] 2015-04-08 12:59
Yes, that would be the solution.

**Comment by jodal** [comment] 2015-04-08 13:12
Great! Closing this then.

**Closed by jodal** 2015-04-08 13:12 UTC
