### ISSUE TITLE
session login() causes segmentation fault

### ISSUE THREAD

**Issue by ttocskcaj** [mopidy/pyspotify#172] opened 2015-08-14 09:59 UTC
Trying this simple code and keep getting Segmentation fault
```python
import spotify
session = spotify.Session()
session.login('user','pass')
```

**Comment by adamcik** [comment] 2015-08-14 10:30
Most likely an application key issue, either the file is not being found, or it might be encoded wrongly. I seem to remember libspotify being bad about this and segfaulting :(

> If you place the application key in the same directory as your application’s main Python file, pyspotify will automatically find it and use it. If you want to keep the application key in another location, you’ll need to set application_key in your session config or call load_application_key_file() to load the session key file correctly.

**Comment by jodal** [comment] 2015-09-04 20:45
Did you find the cause of this?

**Comment by jodal** [comment] 2015-09-09 10:27
I would love to have someone reproduce this, so I can find a way to avoid the segfault...

**Comment by adamcik** [comment] 2015-09-09 10:38
My guess is that this is an other case of bad app key. Sadly libspotify seems to have a bad habit of segfaulting for these :(

**Comment by jodal** [comment] 2015-09-09 10:48
Mhm, but we already check that the appkey is exactly 321 bytes long before passing it on to libspotify. This catches most user errors, like saving the appkey as an ascii hexdump.

**Comment by jodal** [comment] 2016-03-24 22:27
No feedback from reporter in 7 months. Closing as inactionable.

**Closed by jodal** 2016-03-24 22:27 UTC
Labels: bug
