### ISSUE TITLE
request: package python3-spotify to apt.mopidy.com

### ISSUE THREAD

**Issue by akdor1154** [mopidy/pyspotify#170] opened 2015-07-24 05:02 UTC
It would be great if you could publish a deb of pyspotify configured for python3 to your apt repository. Alternatively, is there somewhere I can read up on packaging this myself?

Cheers
Jarrad

**Comment by jodal** [comment] 2015-07-25 07:50
I've already packaged pyspotify2 as a Debian package. The source is in the v2.x/debian branch. Problem is, if I upload it to apt.mopidy.com now, it will be installed in place of pyspotify 1, breaking the mopidy-spotify package. Thus, I won't upload the built package until mopidy-spotify 2 is released.

Closing this as a duplicate of #146.

**Closed by jodal** 2015-07-25 07:50 UTC

**Comment by akdor1154** [comment] 2015-07-25 08:52
ah ok, sorry for the dupe. In the meantime, can you give me a hint towards building from the repo? I've tried dpkg-buildpackage and git-buildpackage, but they fail at the test stage with "can't import spotify._spotify" - I've installed cffi 1.1.3 via the sid source packages.

**Comment by jodal** [comment] 2015-07-25 10:04
I'll see if I can get it built and upload a deb file for you somewhere. Is amd64 good enough for now?

**Comment by akdor1154** [comment] 2015-07-25 11:35
that would be awesome if you could, thanks :)

**Comment by jodal** [comment] 2015-07-25 12:05
I also had the import problem, but that's luckily only a problem with the test run. The package seems to be built correctly with the `spotify._spotify` extension. I've disabled the tests for now and built a 2.0.1 package for amd64:

http://nuh.jodal.no/~jodal/debian/python-spotify_2.0.1-0mopidy1_amd64.deb
http://nuh.jodal.no/~jodal/debian/python3-spotify_2.0.1-0mopidy1_amd64.deb
http://nuh.jodal.no/~jodal/debian/python-spotify-doc_2.0.1-0mopidy1_amd64.deb

**Comment by akdor1154** [comment] 2015-07-25 12:10
ah, awesome! thanks so much. Is it OK to link others to this or would you rather it stay quiet for now? I'm aiming to build an extension to quodlibet (it's py3 based); I'll probably take a while to get moving, though.

**Comment by jodal** [comment] 2015-07-25 12:14
Feel free to use it, but I don't guarantee the link will continue to work forever. The only reason I haven't published it is because of synchronization with Mopidy-Spotify 2. Eventually it'll be available from apt.mopidy.com.

**Comment by akdor1154** [comment] 2015-07-25 12:20
Is it OK to push non-mopidy users towards your repo? If so, I'm really grateful :)

**Comment by jodal** [comment] 2015-07-25 12:31
Yeah, sure. I intend to include apt.mopidy.com in the pyspotify install docs when the package is available there.
