### ISSUE TITLE
Recursion error, same as in #122

### ISSUE THREAD

**Issue by bphermansson** [mopidy/pyspotify#153] opened 2015-03-25 07:10 UTC
Hi
I get the recursion error described in https://github.com/mopidy/pyspotify/issues/122 with 2.0.0b4. The fix in that thread seems to help.

**Comment by jodal** [comment] 2015-03-25 12:17
This has recently surfaced as mopidy/mopidy-spotify#49 too.

**Comment by jodal** [comment] 2015-05-24 08:33
Currently I can't reproduce this. I could blindly disable the `playlist_update_in_progress` event in the hope of it making sure this never happens again. That doesn't feel like a very good solution, and we'll be left without that event forever.

Thus, I opt to close this issue until it resurfaces again, in the hope of ending up with a better solution then.

**Closed by jodal** 2015-05-24 08:33 UTC
Labels: 1 - Ready, bug
